### PR TITLE
Upgraded request to got, made vision client optional ( pass false to disable and use random tf)

### PR DESCRIPTION
**Pull request by Jytesh**
I have tested the non-vision client mode, so please do test if vision client mode works as well, also exposed the siteConfig function, getting siteConfig appears to be slow for me, since its constant you can get it and pass the siteKey and host as options in the future maybe?

Signed-off-by: Jytesh <44925963+Jytesh@users.noreply.github.com>

### CODE REVIEW

**Comment by aw1875** [comment]
I've been looking through the code and testing and it seems like it doesn't seem to work very well and honestly I can't see why anything you did would have this much of an impact but this was the fastest response I got. Nothing you did should be breaking the logic of the code that much but I need to figure out what is happening here before I merge the request.

image

**Comment by Jytesh** [comment]
hmm

**Comment by Jytesh** [comment]
I didn't do anything to affect the visionClient mode so I wonder why thats so slow, ill check it

**Comment by Jytesh** [comment]
I tested it with democaptcha.com, sometimes it gets solved in 15 seconds but sometimes it just keeps requesting and doesnt solve at all... Not sure what the issue is

**Comment by Jytesh** [comment]
Any idea what's wrong

**Comment by aw1875** [comment]
No and unfortunately don't really have the time to figure it out with my work schedule so I'm going to have to close this request for now.

**Pull request closed without merging**
